SIZES = ("S", "M", "L", "XL", "XXL", "3XL")
PROFILE = "mens_regular_long_sleeve_shirt_demo_v1"
MAPPING = dict(
    zip(
        [
            "10585",
            "10525",
            "10145-A",
            "10185",
            "10225",
            "10405",
            "X10",
            "11145",
            "10985",
            "11005",
            "10945",
            "10865",
            "11105",
            "10125",
            "11350",
            "X1",
            "11525",
            "*X98-2",
            "11264",
            "11765",
            "11688",
            "X92",
            "11785",
            "11825",
            "12425-1",
            "12445",
            "12465",
            "12485",
            "12505",
            "11925",
            "12185",
            "12525",
            "10505",
            "12925",
            "12935",
        ],
        [
            "back_length_hps",
            "front_length_hps",
            "half_chest",
            "waist_position_hps",
            "half_waist",
            "half_bottom_opening",
            "hem_curve",
            "yoke_depth_cb",
            "forward_shoulder_neck",
            "forward_shoulder_armhole",
            "shoulder_slope",
            "shoulder_point_to_point",
            "back_mid_armhole",
            "front_mid_armhole",
            "half_armhole_straight",
            "half_bicep",
            "sleeve_cap_height",
            "half_elbow",
            "sleeve_length",
            "cuff_width",
            "cuff_edge_to_edge",
            "sleeve_pleat_depth",
            "sleeve_placket_length",
            "sleeve_placket_width",
            "collar_buttoned_length",
            "collar_outside_edge",
            "collar_width_cb",
            "collar_band_width_cb",
            "collar_point",
            "neck_width",
            "front_neck_drop",
            "tie_gap",
            "front_placket_width",
            "first_button",
            "last_button",
        ],
    )
)
REQUIRED = [
    "back_length_hps",
    "front_length_hps",
    "half_chest",
    "half_waist",
    "half_bottom_opening",
    "yoke_depth_cb",
    "shoulder_slope",
    "shoulder_point_to_point",
    "half_armhole_straight",
    "half_bicep",
    "sleeve_cap_height",
    "sleeve_length",
    "cuff_width",
    "cuff_edge_to_edge",
    "sleeve_placket_length",
    "sleeve_placket_width",
    "collar_width_cb",
    "collar_band_width_cb",
    "neck_width",
    "front_neck_drop",
    "front_placket_width",
]
ASSUMPTIONS = [
    "Demo profile only; client base blocks and physical sample calibration are not supplied.",
    "Body widths allocate half of each flat half-body measurement to each front/back half.",
    "Source shoulder-to-cuff sleeve length includes cuff; sleeve body subtracts cuff width.",
    "Curves use sampled quadratic construction with 24 segments; no shrinkage or additional ease.",
    "Back neck drop is 2 cm. Collar attachment follows generated neckline, not a certified collar block.",
    "Front placket is a center-front extension using the explicitly resolved source width.",
    "Collar point and center-back height use source values; buttoned length and outside edge are checked against source as calibration targets.",
    "Back and yoke are unfolded before nesting. Grain follows the vertical piece axis; no rotation.",
    "Seam allowance defaults to zero. Positive allowance is a polygon offset, not a manufacturing standard.",
    "Pocket omitted because no pocket dimensions are supplied. Sleeve cap mismatch remains a visible warning.",
]
