import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
import {sizes,type Project} from './types';
import {withManualRows} from './manualRows';
import {paletteCommands} from './commands';
type Props={name:string;close:()=>void;project:Project|null;create:(name:string,demo:boolean)=>void;go:(page:string)=>void;save:(changes:Record<string,number>)=>Promise<boolean>;size:string;setSize:(s:string)=>void;allowance:number;setAllowance:(n:number)=>void;busy:boolean;canGenerate?:boolean;hasPattern?:boolean};
export default function Dialogs({name,close,project,create,go,save,size,setSize,allowance,setAllowance,busy,canGenerate=false,hasPattern=false}:Props){
 const ref=useRef<HTMLDialogElement>(null);const [title,setTitle]=useState('New shirt project');const [edits,setEdits]=useState<Record<string,number>>({});const [search,setSearch]=useState('');
 useEffect(()=>{const opener=document.activeElement as HTMLElement|null;const dialog=ref.current;dialog?.showModal();return()=>{dialog?.close();if(opener?.isConnected)opener.focus()}},[]);
 function trapFocus(event:React.KeyboardEvent<HTMLDialogElement>){
  if(event.key!=='Tab')return;
  const controls=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href],[tabindex="0"]')).filter(node=>node.getClientRects().length>0);
  const first=controls[0],last=controls.at(-1);
  if(!first){event.preventDefault();return}
  if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}
  else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}
 }
 return <dialog onKeyDown={trapFocus} aria-labelledby="dialog-title" ref={ref} className={name==='measurements'?'wide-dialog':''} onCancel={close}><header><h2 id="dialog-title">{({projects:'Projects',help:'Workspace guide',settings:'Drafting settings',measurements:'Measurement source table',commands:'Quick actions'} as Record<string,string>)[name]||name}</h2><button className="icon-button" aria-label="Close dialog" onClick={close}><X size={21}/></button></header>
 {name==='projects'&&<><p>Start from your own source files or open the supplied 1078983 example.</p><label>Project name<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="actions"><button disabled={busy||!title.trim()} onClick={()=>create(title,false)}>Start from source files</button><button className="primary" disabled={busy} onClick={()=>create("Men's Regular Fit Shirt (Demo)",true)}>Open demo project</button></div><p>Demo sources: Book2(4).xlsx and 1078983(5).pdf. You’ll review units and drafting assumptions before generation.</p></>}
 {name==='help'&&<><p>Import your measurement workbook and tech-pack PDF. Review values, resolve requirements, and generate a size pattern. Grading uses each size’s actual measurements. Marker nesting arranges cut quantities within the fabric width.</p><h3>Keyboard shortcuts</h3><p>Ctrl+K: quick actions · F: fit canvas · + / −: zoom · Ctrl+Z: undo saved measurement edits · Ctrl+Shift+Z: redo. Drag the empty canvas to pan.</p><h3>Demo boundary</h3><p>This app produces 2D demo patterns. Client production drafting, grading, seam standards and physical sample validation are still required. 3D is unavailable.</p><h3>Document interpretation</h3><p>Local deterministic parsers are active. A cloud AI provider is not configured.</p></>}
 {name==='settings'&&<><p>Demo profile v1. Changes apply to the next generated pattern.</p><label>Seam allowance (cm)<input type="number" min="0" max="3" step="0.1" value={allowance} onChange={e=>setAllowance(Number(e.target.value))}/></label><p>0 cm keeps the seam outline. A positive value adds a uniform offset. This is a demo setting, not a client manufacturing standard.</p><button className="primary" onClick={close}>Apply to next generation</button></>}
 {name==='commands'&&<><input autoFocus placeholder="Search commands…" aria-label="Search commands" value={search} onChange={e=>setSearch(e.target.value)}/><div className="command-list">{paletteCommands(search,{canGenerate,hasPattern}).map(row=><button key={row.id} disabled={Boolean(row.disabled)} title={row.disabled||row.hint} onClick={()=>{if(row.disabled)return;go(row.page);close()}}><span><strong>{row.label}</strong><small>{row.disabled||row.hint}</small></span><kbd>{row.shortcut||'↵'}</kbd></button>)}</div></>}
 {name==='measurements'&&project&&<><div className="table-tools"><input aria-label="Search measurements" placeholder="Search code or measurement…" value={search} onChange={e=>setSearch(e.target.value)}/><label>Editing size<select value={size} onChange={e=>{setSize(e.target.value);setEdits({})}}>{sizes.map(s=><option key={s}>{s}</option>)}</select></label></div><div className="table-scroll"><table><thead><tr><th>Code / Measurement</th>{sizes.map(s=><th key={s}>{s} (cm)</th>)}<th>Tolerance</th><th>Source</th></tr></thead><tbody>{withManualRows(project.measurements).filter(r=>(r.label+r.code).toLowerCase().includes(search.toLowerCase())).map(r=><tr key={r.key}><th><strong>{r.code}</strong><span>{r.label}</span></th>{sizes.map(s=><td key={s} title={`${r.values[s]?.formula||r.values[s]?.raw||''} · ${r.values[s]?.cell||''}`}>{s===size?<input aria-label={`${r.key} ${s}`} type="number" step="0.1" min="0.1" value={edits[r.key]??r.values[s]?.value??''} onChange={e=>setEdits({...edits,[r.key]:Number(e.target.value)})}/>:r.values[s]?.value?.toFixed(2)??'Missing'}{r.values[s]?.formula&&<small>ƒ</small>}{r.values[s]?.override&&<small>edited</small>}</td>)}<td>{r.tolerance??'—'}</td><td>{r.source}<small>{r.sheet} · row {r.row}</small></td></tr>)}</tbody></table></div>{project.measurements.length===0&&<p>Use the main measurement form or import a workbook to populate this table.</p>}<div className="actions"><span>ƒ = evaluated workbook formula · hover for source expression</span><button className="primary" disabled={busy||!Object.keys(edits).length} onClick={async()=>{if(await save(edits))setEdits({})}}>Save table edits</button></div></>}
 </dialog>;
}

