import {useEffect,useRef,useState} from 'react';
import {ZoomIn,ZoomOut,Maximize,RotateCcw} from 'lucide-react';
import type {Pattern,Piece,Point} from './types';
const positions:Record<string,[number,number,number,number]>={Front:[10,15,160,235],Back:[200,15,150,235],Yoke:[385,35,130,60],Collar:[485,135,150,65],'Collar Stand':[485,220,145,50],Sleeve:[30,300,130,220],Cuff:[425,380,100,50],'Sleeve Placket':[355,310,40,160]};
function points(points:Point[]){return points.map(p=>p.join(',')).join(' ')}
type Props={pattern:Pattern|null;selected:string;select:(id:string)=>void;overlays?:Pattern[]};
export default function PatternCanvas({pattern,selected,select,overlays=[]}:Props){
 const [zoom,setZoom]=useState(1);const [pan,setPan]=useState([0,0]);const [grain,setGrain]=useState(true);const [notches,setNotches]=useState(true);const [seam,setSeam]=useState(true);const drag=useRef<number[]|null>(null);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).matches('input,textarea,select'))return;if(e.key==='f'||e.key==='F'){setZoom(1);setPan([0,0])}if(e.key==='+')setZoom(z=>Math.min(z+.1,4));if(e.key==='-')setZoom(z=>Math.max(z-.1,.3));if(e.key==='Escape')select('');};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[select]);
 function piece(p:Piece, offset=0, overlayIndex=0){const [x,y,w,h]=positions[p.name]||[530,410,80,70];const base=pattern?.pieces.find(b=>b.id===p.id)||p;const s=Math.min(w/base.width,h/base.height);const g=p.grainline;const labelY=p.height<20?p.height+14/s:p.height*.76;return <g key={`${p.id}-${offset}-${overlayIndex}`} transform={`translate(${x+offset} ${y}) scale(${s})`} className={selected===p.id?'selected-piece':'pattern-piece'} onClick={()=>select(p.id)} role="button" tabIndex={overlayIndex?-1:0} aria-label={`Select ${p.name}`} aria-pressed={selected===p.id} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(p.id)}}}>
 <polygon points={points(p.points)} strokeDasharray={overlayIndex?'4 2':undefined}/>{seam&&pattern?.seam_allowance!==0&&<polygon className="seam-line" points={points(p.cut_points)}/>}{grain&&<path className="grain-line" d={`M ${g[0][0]} ${g[0][1]} L ${g[1][0]} ${g[1][1]}`} markerStart="url(#arrow)" markerEnd="url(#arrow)"/>}{notches&&p.notches.map((n,i)=><path key={i} d={`M ${n[0]-1} ${n[1]} h 2`}/>)}<text x={p.width/2} y={labelY} fontSize={11/s} textAnchor="middle">{p.name}</text><text x={p.width/2} y={labelY+15/s} fontSize={10/s} textAnchor="middle">{overlayIndex?overlays[overlayIndex-1]?.size:`Cut ${p.quantity}`}</text></g>}
 return <><span className="sr-only" role="status" aria-label="Canvas status" aria-atomic="true">{pattern?.pieces.find(p=>p.id===selected)?.name||'No piece'}{selected?' selected':''}. Zoom {Math.round(zoom*100)}%. Pan {pan[0]}, {pan[1]}.</span><div className="canvas" onKeyDown={e=>{const delta:Record<string,number[]>={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};if(delta[e.key]){e.preventDefault();const [x,y]=delta[e.key];setPan(p=>[p[0]+x,p[1]+y])}}} onWheel={e=>setZoom(z=>Math.max(.3,Math.min(4,z+(e.deltaY<0?.08:-.08))))}><svg role="group" tabIndex={0} aria-describedby="canvas-instructions" viewBox="0 0 660 550" aria-label="2D shirt pattern canvas" onPointerDown={e=>{if(e.button===1||e.target===e.currentTarget){drag.current=[e.clientX-pan[0],e.clientY-pan[1]];e.currentTarget.setPointerCapture(e.pointerId)}}} onPointerMove={e=>{if(drag.current)setPan([e.clientX-drag.current[0],e.clientY-drag.current[1]])}} onPointerUp={()=>drag.current=null}><defs><marker id="arrow" viewBox="0 0 10 10" refX="5" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M 10 5 L 0 0 L 0 10 Z" fill="currentColor"/></marker></defs><g transform={`translate(${pan[0]} ${pan[1]}) scale(${zoom})`}>{pattern?.pieces.map(p=>piece(p))}{pattern?.pieces.filter(p=>p.name==='Sleeve').map(p=>piece(p,160))}{overlays.map((o,i)=><g key={o.id} className={`grade-overlay grade-${i}`}>{o.pieces.map(p=>piece(p,0,i+1))}</g>)}</g>{!pattern&&<g className="canvas-empty"><text x="330" y="250" textAnchor="middle">Your pattern starts with measurements</text><text x="330" y="277" textAnchor="middle" fontSize="13">Review requirements, then generate your first pattern.</text></g>}</svg></div>
 <span id="canvas-instructions" className="sr-only">Use Tab to select a piece, Enter to inspect, arrow keys to pan, plus or minus to zoom, and F to fit.</span>{pattern&&<details className="canvas-table sr-only"><summary>Accessible piece summary</summary><table><caption>Pattern pieces and construction quantities</caption><thead><tr><th scope="col">Piece</th><th scope="col">Width</th><th scope="col">Height</th><th scope="col">Cut</th></tr></thead><tbody>{pattern.pieces.map(p=><tr key={p.id}><th scope="row">{p.name}</th><td>{p.width}</td><td>{p.height}</td><td>{p.quantity}</td></tr>)}</tbody></table></details>}<div className="canvas-toolbar"><button className="icon-button" aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(z+.1,4))}><ZoomIn size={20}/></button><button className="icon-button" aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(z-.1,.3))}><ZoomOut size={20}/></button><button onClick={()=>{setZoom(1);setPan([0,0])}} aria-label="Reset zoom">{Math.round(zoom*100)}% <RotateCcw size={13}/></button><button className="icon-button" aria-label="Fit all" onClick={()=>{setZoom(1);setPan([0,0])}}><Maximize size={19}/></button>{[[notches,setNotches,'Show Notches'],[grain,setGrain,'Show Grainline'],[seam,setSeam,'Show Seam Allowance']].map(([v,set,label])=><label key={String(label)}><input type="checkbox" checked={Boolean(v)} onChange={e=>(set as (v:boolean)=>void)(e.target.checked)}/>{String(label)}</label>)}</div></>;
}
