import {CheckCircle2,RefreshCw,Scissors,Box,ArrowRight} from 'lucide-react';
import {sizeLabels,type Pattern,type Project} from './types';
import PatternCanvas from './PatternCanvas';
const PIECE_ORDER=['Front','Back','Yoke','Sleeve','Collar','Collar Stand','Cuff','Sleeve Placket'];
type Props={project:Project;pattern:Pattern|null;size:string;page:string;selected:string;select:(id:string)=>void;go:(page:string)=>void;generate:()=>void;busy:boolean;validate:()=>void};
export default function Preview({project:p,pattern,size,page,selected,select,go,generate,busy,validate}:Props){
 const piece=pattern?.pieces.find(p=>p.id===selected);
 const label=sizeLabels[size]||size;
 const ordered=[...(pattern?.pieces||[])].sort((a,b)=>PIECE_ORDER.indexOf(a.name)-PIECE_ORDER.indexOf(b.name));
 const measurement=(key:string,factor=1)=>{const v=p.measurements.find(r=>r.key===key)?.values[size]?.value;return v==null?'—':`${(v*factor).toFixed(1)} cm`};
 return <div className="preview-column"><section className="preview-panel card"><div className="preview-header"><div><h2>{page==='Pattern Studio'?'Pattern Studio':'Pattern Preview'}</h2><p>2D pattern pieces generated from your measurements</p></div><div className="tabs"><button className="primary">2D Pattern</button><button disabled title="3D simulation is outside the demo scope">3D Preview</button><button disabled title="Garment simulation is outside the demo scope">Garment View</button></div></div>{pattern?.stale&&<div className="notice">Measurements changed. This preview is from the previous version; regenerate before export.</div>}
 <div className="preview-grid"><div className="canvas-column"><PatternCanvas pattern={pattern} selected={selected} select={select} overlays={page==='Grading'?p.grades.filter(g=>g.size!==size):[]}/></div><aside className="info-rail"><section className="info-box"><h3>{piece?piece.name:'Pattern Info'}</h3><dl>{(piece?[['Size',label],['Cut quantity',String(piece.quantity)],['Width',`${piece.width.toFixed(2)} cm`],['Height',`${piece.height.toFixed(2)} cm`],['Area',`${piece.area.toFixed(1)} cm²`],['Perimeter',`${piece.perimeter.toFixed(1)} cm`],['Fold',piece.cut_on_fold?'Unfolded for marker':'No']]:[['Garment',"Men's Shirt"],['Fit','Regular Fit'],['Size',sizeLabels[pattern?.size||size]||pattern?.size||size],['Total Pieces',String(pattern?.pieces.length||0)],['Unit','cm'],['Seam Allowance',`${Number(pattern?.seam_allowance??0).toFixed(1)} cm`],['Notches','Yes'],['Grainlines','Yes']]).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section><section className="info-box actions-box"><h3>Actions</h3><button className="primary" disabled={busy} onClick={generate}><RefreshCw size={16}/>{pattern?'Regenerate Pattern':'Generate Pattern'}</button><button onClick={()=>go('Pattern Studio')}><Scissors size={19}/>Edit in Studio</button><button disabled title="Not available in this 2D MVP"><Box size={19}/>View 3D Preview</button>{page==='Pattern Studio'&&<button onClick={validate} disabled={!pattern||busy}>Validate pattern</button>}</section></aside></div></section>
 <div className="summary-row"><section className="card"><h3>Measurement Summary</h3><dl>{[['Size',label],['Chest',measurement('half_chest',2)],['Waist',measurement('half_waist',2)],['Shoulder',measurement('shoulder_point_to_point')],['Sleeve',measurement('sleeve_length')]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section><section className="card"><h3>Pattern Pieces ({pattern?.pieces.length||0})</h3><div className="piece-list">{ordered.map(piece=><button key={piece.id} onClick={()=>select(piece.id)} className={selected===piece.id?'chosen':''}><CheckCircle2 size={14}/>{piece.name} ({piece.quantity})</button>)||<p>Generate your first pattern.</p>}</div></section><section className="card next-step"><h3>Next Step</h3><strong className={pattern?'success':''}>{pattern?'Pattern generated successfully!':'Review your measurements'}</strong><p>{pattern?'You can now review in Pattern Studio, make adjustments, or export the files.':'Confirm the source data and choose your drafting profile.'}</p><button className="primary" onClick={()=>go(pattern?'Pattern Studio':'Requirements')}>{pattern?'Go to Pattern Studio':'Review Requirements'}<ArrowRight size={18}/></button></section></div>
 {page==='Pattern Studio'&&<section className="card validation"><h3>Validation & provenance</h3>{pattern?.validation.map((v,i)=><button key={i} className={v.severity==='PASS'?'success':'warning'} onClick={()=>select(pattern.pieces.find(p=>p.name===v.piece)?.id||'')}>{v.severity}: {v.message}</button>)}<details><summary>Drafting assumptions and input fingerprint</summary><p>{pattern?.input_hash}</p>{pattern?.assumptions.map(a=><p key={a}>{a}</p>)}</details></section>}</div>;
}
