import {Ruler,ClipboardCheck,FileText,Scissors,Layers,Grid3X3,Upload,HelpCircle,Settings,ChevronDown,Check,Plus} from 'lucide-react';
import type {Project} from './types';
import BrandMark from './BrandMark';
import DemoShirt from './DemoShirt';
export const navigation=['Measurements','Requirements','Generate Pattern','Pattern Studio','Grading','Marker Nesting','Export'];
const icons=[Ruler,ClipboardCheck,FileText,Scissors,Layers,Grid3X3,Upload];
type Props={project:Project|null;page:string;go:(page:string)=>void;open:(name:string)=>void;projects:{id:string;name:string}[];choose:(id:string)=>void;askAi?:()=>void};
export default function Shell({project,page,go,open,projects,choose,askAi}:Props){
 return <><header className="topbar"><div className="brand"><BrandMark/><div><strong>Garment Pattern Maker V5</strong><span>From Measurements to Production-Ready Patterns</span></div></div><div className="utility"><label className="project-picker">Project: <select aria-label="Project" value={project?.id||''} onChange={e=>choose(e.target.value)}><option value="" disabled>Select project</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="icon-button" aria-label="New project" onClick={()=>open('projects')}><Plus size={17}/></button><div className="utility-right">{askAi&&<button type="button" data-ask-ai onClick={askAi}>Ask AI</button>}<button onClick={()=>open('help')}><HelpCircle size={16}/> Help</button><button onClick={()=>open('settings')}><Settings size={17}/> Settings</button><span className="avatar">U</span><button onClick={()=>open('projects')}>User <ChevronDown size={15}/></button></div></div></header>
 <aside className="sidebar"><nav>{navigation.map((n,i)=>{const Icon=icons[i];return <button key={n} className={page===n?'active':''} onClick={()=>go(n)}><Icon size={24}/><span>{i+1}</span>{n}</button>})}</nav><div className="demo-card"><p className="demo-title">Men’s Regular Fit Long Sleeve Shirt</p><DemoShirt className="shirt-outline"/>{['Deterministic Drafting','Configurable Rules','No AI Hallucination','Customer Demo Ready'].map(t=><div className="demo-point" key={t}><Check size={14}/>{t}</div>)}</div><small className="version">v5.0.0</small></aside>
 <div className="stepper">{['Measurements','Requirements','Generate Pattern','Review & Edit','Export'].map((n,i)=>{const target=i===3?'Pattern Studio':n;return <button key={n} onClick={()=>go(target)} className={page===target?'current':''}><b>{i+1}</b><span><strong>{n}</strong><small>{['Upload or enter measurements','Check missing information','Create pattern pieces','Visualize and adjust','Download files'][i]}</small></span>{i<4&&<i/>}</button>})}</div></>;
}
